version: '3.7'

services:
  sgtm:
    image: moul/sgtm:latest
    restart: on-failure
    volumes:
      - .:/app
    working_dir: /app
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    command:
      run
    ports:
      - 8000
    environment:
      - VIRTUAL_HOST=sgtm.place
      - VIRTUAL_PORT=8000
    networks:
      - default
      - service-proxy

networks:
  service-proxy:
    external: true
