version: '3.7'

services:
  sgtm-server:
    image: moul/sgtm:latest
    restart: on-failure
    volumes:
      - .:/app
      - "/etc/localtime:/etc/localtime:ro"
    working_dir: /app
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    command: --enable-server run
    ports:
      - 8000
    environment:
      - VIRTUAL_HOST=sgtm.club
      - VIRTUAL_PORT=8000
    networks:
      - default
      - service-proxy

  sgtm-discord:
    image: moul/sgtm:latest
    restart: on-failure
    volumes:
      - .:/app
    working_dir: /app
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    command: --enable-discord run
    networks:
      - default

networks:
  service-proxy:
    external: true
